// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: kb_index_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KBIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url         string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Tag         string `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Key         string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Indexed     uint32 `protobuf:"varint,6,opt,name=indexed,proto3" json:"indexed,omitempty"`
	KbId        string `protobuf:"bytes,7,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
}

func (x *KBIndexRequest) Reset() {
	*x = KBIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kb_index_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KBIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KBIndexRequest) ProtoMessage() {}

func (x *KBIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kb_index_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KBIndexRequest.ProtoReflect.Descriptor instead.
func (*KBIndexRequest) Descriptor() ([]byte, []int) {
	return file_kb_index_service_proto_rawDescGZIP(), []int{0}
}

func (x *KBIndexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KBIndexRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *KBIndexRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *KBIndexRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KBIndexRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KBIndexRequest) GetIndexed() uint32 {
	if x != nil {
		return x.Indexed
	}
	return 0
}

func (x *KBIndexRequest) GetKbId() string {
	if x != nil {
		return x.KbId
	}
	return ""
}

type KBIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *KBIndexReply) Reset() {
	*x = KBIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kb_index_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KBIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KBIndexReply) ProtoMessage() {}

func (x *KBIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_kb_index_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KBIndexReply.ProtoReflect.Descriptor instead.
func (*KBIndexReply) Descriptor() ([]byte, []int) {
	return file_kb_index_service_proto_rawDescGZIP(), []int{1}
}

func (x *KBIndexReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_kb_index_service_proto protoreflect.FileDescriptor

var file_kb_index_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6b, 0x62, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xab, 0x01, 0x0a, 0x0e, 0x4b, 0x42, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65,
	0x64, 0x12, 0x13, 0x0a, 0x05, 0x6b, 0x62, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6b, 0x62, 0x49, 0x64, 0x22, 0x1e, 0x0a, 0x0c, 0x4b, 0x42, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x94, 0x01, 0x0a, 0x0e, 0x4b, 0x42, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x4b, 0x42, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x4b, 0x42, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12,
	0x0f, 0x2e, 0x4b, 0x42, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x4b, 0x42, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x2a, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x4b, 0x42,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x4b,
	0x42, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kb_index_service_proto_rawDescOnce sync.Once
	file_kb_index_service_proto_rawDescData = file_kb_index_service_proto_rawDesc
)

func file_kb_index_service_proto_rawDescGZIP() []byte {
	file_kb_index_service_proto_rawDescOnce.Do(func() {
		file_kb_index_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_kb_index_service_proto_rawDescData)
	})
	return file_kb_index_service_proto_rawDescData
}

var file_kb_index_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kb_index_service_proto_goTypes = []interface{}{
	(*KBIndexRequest)(nil), // 0: KBIndexRequest
	(*KBIndexReply)(nil),   // 1: KBIndexReply
}
var file_kb_index_service_proto_depIdxs = []int32{
	0, // 0: KBIndexService.Create:input_type -> KBIndexRequest
	0, // 1: KBIndexService.Modify:input_type -> KBIndexRequest
	0, // 2: KBIndexService.Delete:input_type -> KBIndexRequest
	1, // 3: KBIndexService.Create:output_type -> KBIndexReply
	1, // 4: KBIndexService.Modify:output_type -> KBIndexReply
	1, // 5: KBIndexService.Delete:output_type -> KBIndexReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kb_index_service_proto_init() }
func file_kb_index_service_proto_init() {
	if File_kb_index_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kb_index_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KBIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kb_index_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KBIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kb_index_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kb_index_service_proto_goTypes,
		DependencyIndexes: file_kb_index_service_proto_depIdxs,
		MessageInfos:      file_kb_index_service_proto_msgTypes,
	}.Build()
	File_kb_index_service_proto = out.File
	file_kb_index_service_proto_rawDesc = nil
	file_kb_index_service_proto_goTypes = nil
	file_kb_index_service_proto_depIdxs = nil
}
